name: Install dependencies

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Verify installation
        run: poetry show

      - name: Run tests
        run: poetry run pytest

      - name: Coverage Badge
        uses: actions/checkout@v4
      - name: Generate coverage report
        run: |
          poetry run pytest --cov=your_package tests/
          poetry run coverage xml
      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-py@v2