name: Install dependencies
permissions:
  id-token: write
  attestations: write
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Verify installation
        run: poetry show

      - name: Run tests
        run: poetry run pytest

      - name: Coverage Badge
        uses: actions/checkout@v4
      - name: Generate coverage report
        run: |
          pip install coverage
          poetry run coverage run -m pytest
          poetry run  coverage report -m
      - name: Generate Coverage Badge
        id: coverage-badge-py
        uses: tj-actions/coverage-badge-py@v2