- name: Install dependencies
  on: [push, pull_request]

  jobs:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev